# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.        
permalink:          /:title/


# Setup
title:               NL2Bash-Complex
tagline: "Synthesis Complex Bash Scripts from Natural Language"
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Xingyu Wei
  email:             aczzdx@gmail.com

# Custom vars
version:             1.0.0


# plugins
plugins: [jekyll-paginate]
