# Permalinks
#

# Setup
title:               "The quick brown dog jumps over the lazy fox"
baseurl:             'https://aczzdx.github.io'
# baseurl: ""
paginate:            5

# About/contact
author:
  name:              Xingyu Wei
  email:             aczzdx@gmail.com

# Custom vars
version:             1.0.0


# plugins
plugins:
  - jekyll-paginate
  - jemoji
